name: ganbaro_game
description: "A professional physics game project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # 確実に解決できるバージョンに修正しました
  flame: ^1.11.0
  flame_forge2d: ^0.18.1
  cupertino_icons: ^1.0.8
  audioplayers: ^6.6.0
  shared_preferences: ^2.5.5
  google_mobile_ads: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1  # ←これを追加

flutter:
  uses-material-design: true
  # ここから下を追記
  assets:
    - assets/audio/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  remove_alpha_ios: true # iOS用に透過(アルファチャンネル)を自動削除する設定